# Generated by Django 5.1.7 on 2025-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_mode',
            new_name='cart_code',
        ),
    ]
